services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        ports:
            - 8000:80
        volumes:
            - .:/var/www/html
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: stickers
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        depends_on:
            - db

volumes:
    db_data:
